language: ruby
rvm: 2.0.0

before_install:
  # Fix error: Incorrect file permissions (664)
  - chmod 644 Formula/*.rb
  - umask 022
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - mkdir -p $HOME/.linuxbrew
  - curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
  - rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)"
  - mkdir -p "$(brew --repo $TRAVIS_REPO_SLUG)"
  - rsync -az "$TRAVIS_BUILD_DIR/" "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export TRAVIS_BUILD_DIR="$(brew --repo $TRAVIS_REPO_SLUG)"
  - cd "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot

notifications:
  slack:
    secure: GBwoqR+LsY/RiJGpfI4xVsfrQ2CGk9YnDQbrIdd3vLs2IxnI7NmRRhG6Bwx/wgj0s2iHH3PBKkXJHVCCmJatOqPExJMYYS+HDE22S7FKkcSNjEeXQQxMfyDlAH84aUCDIB+4y7hHEuhGHasVhL/TF6ukLcSjkvpwHB721j/az3uXtGC+srIrxJHSx+TsEDoBZoQubhaNUP+NfW+ONzR3qqTlP0UFiHZH5KujgsLICPAeOaO+Bj6MFQtRhxchfuZGGCpLZYHagQSaUpeAIaXRZ8iT82KmbV1m2HScHLM9hih7Xo9aEbT1Pky/YMx7Dw9r6WBqDUSMQ2GRZ5AYlzqItthd8Ym/cMCsfoRVqOba+W20fGG7stvtdk56csOebpJ/PeN8Hfz5NUDegEb7K6xDo1xQvKLcJ19oB30SwPzAnMdmbHIWZsdpozkIaHbdGHl3yu2xkTp8cn/TKR2CGsBdsRWYh+6Tch4+yeceS/En1/gD1G73LoaaNLfY0GS8d66qIZe0jUA3mRV6/mtSu0PCKu+B5tP2d1uq0lIJijosHEB33bVl4FjBmBdngGzvGrSq8AJyRuc1Q+7L9FoBFT3M65mkRVY6qNX+EnNUfEtsZ1IDBxVV7443bCuOwtaZGcfwZqdf1eUbeQZ+pWAfBUbKzyojKJnas0LNI5ElIn8usaY=
  email:
    on_success: never
    on_failure: always
