name: Build bottles from core merge request

on: repository_dispatch

jobs:
  bottling:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@master
      - name: Setup user
        run: |
          sudo adduser $(whoami) linuxbrew
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s "$GITHUB_WORKSPACE" $(brew --repository ${{github.repository}})
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --git-name=LinuxbrewTestBot \
            --git-email=testbot@linuxbrew.sh \
            --keep-old ${{github.event.client_payload.formula}}
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --git-name=LinuxbrewTestBot \
            --git-email=testbot@linuxbrew.sh \
            --ci-upload --publish \
            --keep-old ${{github.event.client_payload.formula}}
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Push bottles
        run: |
          cd "$(brew --repo ${{github.repository}})"
          git show
          git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master
