name: Build bottles from core merge request

on: repository_dispatch

jobs:
  bottling:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@master
      - name: Setup user
        run: |
          echo ::group::${{github.event.client_payload.formula}} requested by ${{github.event.client_payload.name}}
          echo ::endgroup::
          sudo adduser $(whoami) linuxbrew
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s "$GITHUB_WORKSPACE" $(brew --repository ${{github.repository}})
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --git-name=LinuxbrewTestBot \
            --git-email=testbot@linuxbrew.sh \
            --keep-old ${{github.event.client_payload.formula}}
      - name: Upload bottles
        env:
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
        run: |
          cd "$(brew --repo ${{github.repository}})"
          git fetch origin
          git reset --hard origin/master
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --git-name=LinuxbrewTestBot \
            --git-email=testbot@linuxbrew.sh \
            --ci-upload --publish \
            --keep-old ${{github.event.client_payload.formula}}
      - name: Push bottles
        run: |
          cd "$(brew --repo ${{github.repository}})"
          msg=$(git show -s --format=format:%s)
          git commit --amend -m "$msg\n\nCo-authored-by: ${{github.event.client_payload.name}} <${{github.event.client_payload.email}}>"
          git show
          git fetch
          git rebase origin/master
          git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master
