name: Start VM
on:
  pull_request_target:
    paths-ignore:
      - "Formula/patchelf.rb"
      - "Formula/binutils.rb"
jobs:
  start_vm:
    if: github.repository == 'Homebrew/linuxbrew-core' && contains(github.event.pull_request.labels.*.name, 'self-hosted-ci')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Start VM
        run: gcloud compute instances start --zone=europe-west1-b linuxbrew-core1
      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@master
        if: always()
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          def: |
            [
                {
                    "label": "linuxbrew-core1",
                    "status": "added",
                }
            ]
