name: Stop VM
on:
  workflow_run:
    workflows:
      - "SelfHosted"
    types:
      - completed
jobs:
  stop_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Stop VM
        run: gcloud compute instances stop --zone=europe-west1-b linuxbrew-core1
