name: SelfHosted

on:
  pull_request:
    types:
      - labeled
    paths:
      - "Formula/**"

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
jobs:
  get-runner-name-from-label:
    runs-on: ubuntu-latest
    if: github.repository == 'Homebrew/linuxbrew-core' && contains(github.event.pull_request.labels.*.name, 'self-hosted-ci')
    outputs:
      runner: ${{ steps.runner-from-label.outputs.runner }}
    steps:
      - name: Get self hosted runner name from label
        id: runner-from-label
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { labels: labels } } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            if (!labels.map(label => label.name).includes('linux-self-hosted')) {
              const regex = /linux-self-hosted-([0-9]+)/;
              var runner = labels.filter(item => item.name.match(regex))[0].name;
              console.log('Found self-hosted runner: ' + runner);
              return "::set-output name=runner::${runner}";
            }
