name: GitHub Actions CI

on: pull_request

jobs:
  tap_syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        run: |
          HOMEBREW_PREFIX="$(brew --prefix)"
          HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX/Homebrew"
          HOMEBREW_CORE_REPOSITORY="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
          brew update-reset "$HOMEBREW_REPOSITORY"
          export PATH="$HOMEBREW_PREFIX/bin:$PATH"
          echo "::add-path::$HOMEBREW_PREFIX/bin"
          GEMS_PATH="$HOMEBREW_REPOSITORY/Library/Homebrew/vendor/bundle/ruby/"
          echo "::set-output name=gems-path::$GEMS_PATH"
          GEMS_HASH=$(shasum -a 256 "$HOMEBREW_REPOSITORY/Library/Homebrew/Gemfile.lock" | cut -f1 -d' ')
          echo "::set-output name=gems-hash::$GEMS_HASH"
          cd $(brew --repo ${{github.repository}})
          git fetch origin "${{github.sha}}"
          git checkout --force -B master FETCH_HEAD

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Install taps
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew tap homebrew/test-bot

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax

  tests:
    needs: tap_syntax
    if: startsWith(github.event.pull_request.title, 'Merge') == false
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Update Homebrew
        run: brew update-reset

      - name: Set up Git repository
        run: |
          cd $(brew --repo ${{github.repository}})
          git clean -ffdx
          git fetch --prune --force origin master
          git fetch --prune --force origin ${{github.sha}}
          git checkout --force ${{github.sha}}
          git log -1

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --keep-old

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          cat ~/bottles/steps_output.txt
          rm ~/bottles/steps_output.txt

      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"

      - name: Move bottles
        if: always() && steps.bottles.outputs.count > 0
        run: mv ~/bottles $GITHUB_WORKSPACE

      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
