name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == false && github.event.pusher.name != 'BrewTestBot' && github.repository == 'Homebrew/linuxbrew-core'
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew
        run: brew update-reset
      - name: Determine associated pull request
        uses: actions/github-script@0.9.0
        id: pr
        with:
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              throw "No pull requests are associated with this merge commit."
            }
            core.setOutput("number", prs.data[0].number.toString())
            core.setOutput("head_sha", prs.data[0].head.sha)
      - name: Download workflow artifacts
        uses: Homebrew/actions/download-artifact@master
        with:
          github_token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          workflow: tests.yml
          commit: ${{steps.pr.outputs.head_sha}}
          name: bottles
          path: bottles
      - name: Upload and publish bottles
        env:
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        if: steps.pr.outputs.number != 0
        run: |
          cd bottles
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old
      - name: Push bottle commit
        env:
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        if: steps.pr.outputs.number != 0
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 20); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@github.com/${{github.repository}} master; then
              exit 0
            else
              max=$(( $try + 10 ))
              sleep $(shuf -i 3-$max -n 1)
            fi
          done
          exit 1

      - name: Post comment on failure
        if: ${{!success()}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          issue: ${{setps.pr.outputs.number}}
          body: ':warning: @${{github.actor}} bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot_body: ':warning: Bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot: BrewTestBot
