name: Upload bottles

on:
  push:
    branches: [master]

jobs:
  upload-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Get artifact data
        uses: actions/github-script@0.4.0
        id: artifact
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: "e2575cfdc20129b94f8268a3b9594ca61f21f4b0"
            })
            console.log(prs)
            console.log(prs.data)
            console.log(prs.length + " prs")
            const pr = prs[0]
            console.log("first pr head ref=" + pr.head.ref)
            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build-bottles.yml",
              branch: pr.head.ref
              })
            console.log(runs)
            console.log(runs.total_count + " runs")
            const artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runs.workflow_runs[0].id
              })
            console.log(artifacts)
            console.log(artifacts.total_count + " artifacts")
            console.log("Artifact <" + artifacts[0].archive_download_url + ">")
            return {id: artifacts[0].id, success: true}
      - name: Download artifacts
        env:
          HOMEBREW_BINTRAY_USER: linuxbrewtestbot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
        if: steps.artifact.outputs.success
        run: |
          set -eu
          artifact_id=${{steps.artifact.outputs.id}}
          curl -L -o bottles.zip "https://${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@api.github.com/repos/${{github.repository}}/actions/artifacts/$artifact_id/zip"
          file bottles.zip
          unzip bottles.zip
          brew test-bot --ci-upload --publish --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --keep-old
          cd "$(brew --repo ${{github.repository}})"
          git fetch
          git rebase origin/master
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}} master
